# Form implementation generated from reading ui file '../../mainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainMenuWindow(object):
    def setupUi(self, mainMenuWindow):
        mainMenuWindow.setObjectName("mainMenuWindow")
        mainMenuWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        mainMenuWindow.resize(469, 553)
        self.verticalLayout = QtWidgets.QVBoxLayout(mainMenuWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainMenu = QtWidgets.QVBoxLayout()
        self.MainMenu.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.MainMenu.setObjectName("MainMenu")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.MainMenu.addItem(spacerItem)
        self.welcomeMessage = QtWidgets.QLabel(parent=mainMenuWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomeMessage.sizePolicy().hasHeightForWidth())
        self.welcomeMessage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.welcomeMessage.setFont(font)
        self.welcomeMessage.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.welcomeMessage.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.welcomeMessage.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.welcomeMessage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcomeMessage.setObjectName("welcomeMessage")
        self.MainMenu.addWidget(self.welcomeMessage)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.MainMenu.addItem(spacerItem1)
        self.cookbooksButton = QtWidgets.QPushButton(parent=mainMenuWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookbooksButton.sizePolicy().hasHeightForWidth())
        self.cookbooksButton.setSizePolicy(sizePolicy)
        self.cookbooksButton.setMinimumSize(QtCore.QSize(256, 40))
        self.cookbooksButton.setFlat(False)
        self.cookbooksButton.setObjectName("cookbooksButton")
        self.MainMenu.addWidget(self.cookbooksButton)
        self.manualRecipeButton = QtWidgets.QPushButton(parent=mainMenuWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualRecipeButton.sizePolicy().hasHeightForWidth())
        self.manualRecipeButton.setSizePolicy(sizePolicy)
        self.manualRecipeButton.setMinimumSize(QtCore.QSize(256, 40))
        self.manualRecipeButton.setObjectName("manualRecipeButton")
        self.MainMenu.addWidget(self.manualRecipeButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.urlRecipeButton = QtWidgets.QPushButton(parent=mainMenuWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlRecipeButton.sizePolicy().hasHeightForWidth())
        self.urlRecipeButton.setSizePolicy(sizePolicy)
        self.urlRecipeButton.setMinimumSize(QtCore.QSize(256, 40))
        self.urlRecipeButton.setObjectName("urlRecipeButton")
        self.MainMenu.addWidget(self.urlRecipeButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.MainMenu.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.MainMenu)

        self.retranslateUi(mainMenuWindow)
        QtCore.QMetaObject.connectSlotsByName(mainMenuWindow)
        mainMenuWindow.setTabOrder(self.cookbooksButton, self.manualRecipeButton)
        mainMenuWindow.setTabOrder(self.manualRecipeButton, self.urlRecipeButton)

    def retranslateUi(self, mainMenuWindow):
        _translate = QtCore.QCoreApplication.translate
        mainMenuWindow.setWindowTitle(_translate("mainMenuWindow", "Groshy: Action Selection"))
        self.welcomeMessage.setText(_translate("mainMenuWindow", "Welcome to Goshy"))
        self.cookbooksButton.setText(_translate("mainMenuWindow", "View CookBooks"))
        self.manualRecipeButton.setText(_translate("mainMenuWindow", "Enter Recipe Manually"))
        self.urlRecipeButton.setText(_translate("mainMenuWindow", "Enter Recipe URL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainMenuWindow = QtWidgets.QWidget()
    ui = Ui_mainMenuWindow()
    ui.setupUi(mainMenuWindow)
    mainMenuWindow.show()
    sys.exit(app.exec())
